
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Pagetransition from "@/components/pagetransition";
import Stairtransition from "@/components/ui/stairtransition";
import Services from "./services/page";
import {  Toaster } from 'react-hot-toast';
import Footer from "./footer/page";



const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

 export const metadata = {
   title: "My Portfolio",
   description: "Generated by Muhammedhsbo",
  
 };



export default function RootLayout({ children }) {
 

 
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} font-sans `}>
        <Stairtransition/>
        <Pagetransition >
            <Toaster />
            <Header />
          {children}
          <Footer />
          </Pagetransition>
      </body>
    </html>
  );
}
